'use client'
import { useEffect, useState } from 'react'
import { use } from 'react'
import { useAdminAuth } from '@/context/AdminAuthContext'
import { useRouter } from 'next/navigation'
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000'
type Note={id:string;author:string;role:string;content:string;createdAt:string}
type Designer={id:string;name:string;email:string;specialty:string;location:string;status:string;joined:string;bio:string;phone:string;yearsOfExperience:number;inquiries:number;bookings:number;notes:Note[]}
export default function Page({params}:{params:Promise<{id:string}>}){const {id}=use(params);const {admin}=useAdminAuth();const r=useRouter();const [d,setD]=useState<Designer|null>(null);const [note,setNote]=useState('');useEffect(()=>{fetch(`${API_URL}/designers/${id}`).then(x=>x.json()).then(setD).catch(()=>{})},[id]);if(!admin)return null;if(!d)return <div>Loading...</div>;const save=async(content:string)=>{await fetch(`${API_URL}/designers/${id}/notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({author:admin.name,role:admin.role,content})});const x=await fetch(`${API_URL}/designers/${id}`);setD(await x.json())};const status=async(s:string)=>{await fetch(`${API_URL}/designers/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s})});setD({...d,status:s});};return <main className="p-6 max-w-3xl mx-auto space-y-6"><button onClick={()=>r.push('/admin/dashboard')}>Back</button><div className="bg-white p-6 rounded-2xl border"><h1 className="text-xl font-bold">{d.name}</h1><p className="text-sm text-gray-500">{d.email}</p><p className="mt-2">{d.bio}</p><div className="mt-4 flex gap-2 flex-wrap">{['Pending','Verified','Active','Suspended','Rejected'].map(s=><button key={s} onClick={()=>status(s)} className="px-3 py-1 rounded-full border text-xs">{s}</button>)}</div></div><div className="bg-white p-6 rounded-2xl border"><h2 className="font-semibold mb-3">Notes</h2>{d.notes.map(n=><div key={n.id} className="mb-3 border-b pb-3"><p className="text-xs text-gray-400">{n.author} · {n.createdAt}</p><p className="text-sm">{n.content}</p></div>)}<textarea className="w-full border rounded-xl p-3" rows={3} value={note} onChange={e=>setNote(e.target.value)} /><button onClick={()=>{if(note.trim())save(note.trim()).then(()=>setNote(''))}} className="mt-3 px-4 py-2 rounded-xl bg-amber-500 text-white">Add Note</button></div></main>}
